[package]
name = "dbeer_rs"
version = "0.1.0"
edition = "2021"
authors = ["Javier Orfo"]
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.4.2", features = [ "neovim-0-9", "mlua" ] }
chrono = "0.4.38"
